Docker 4
Otus-DevOps-2022-11/AvallaSD_microservices pull request #4
Opened 2023-03-26 14:45 UTC by AvallaSD

# Выполнено ДЗ №

 - [ ] Основное ДЗ
 - [ ] Задание со *

## В процессе сделано:
 - Пункт 1
 - Пункт 2

## Как запустить проект:
 - Например, запустить команду X в директории Y

## Как проверить работоспособность:
 - Например, перейти по ссылке http://localhost:8080

## PR checklist
 - [ ] Выставил label с номером домашнего задания
 - [ ] Выставил label с темой домашнего задания

2023-03-28 09:38 UTC, mrgreyves requested changes
Здравствуйте!)
У вас не хватает файла docker-compose.yml
Нужно добавить
ДЗ возвращаю на доработку

2023-03-30 15:52 UTC, mrgreyves requested changes
https://github.com/Otus-DevOps-2022-11/AvallaSD_microservices/actions/runs/4542267388/jobs/8005472519?pr=4#step:4:162
Не туда добавили
В директории src надо =)

2023-04-07 09:45 UTC, mrgreyves requested changes
Здравствуйте!)
А где у вас код приложений то?

2023-04-09 09:17 UTC, AvallaSD commented
Добрый день!
Не очень понимаю вопрос. Код приложений находится в папке src

2023-04-16 08:15 UTC, merged